### ISSUE TITLE
TypeError: owner.lookup is not a function in Acceptance tests

### ISSUE THREAD

**Issue by bmrsny** [tim-evans/ember-plupload#64]
Trying to use the Plupload Test Helpers, and can't get past the `addFiles` function...

acceptance test
```
import { test } from 'qunit';
import moduleForAcceptance from 'uma/tests/helpers/module-for-acceptance';
import { addFiles } from 'ember-plupload/test-helper';
moduleForAcceptance('Acceptance | uploads');

test('uploading a csv', function (assert) {
let [file] = addFiles(this.application, 'csv-uploader', {
    name: 'ember.csv',
  });
});
```
backtrace
```Source:     
TypeError: owner.lookup is not a function
    at addFiles (http://localhost:7357/assets/vendor.js:136549:26)
    at Object.<anonymous> (http://localhost:7357/assets/tests.js:170:59)
    at runTest (http://localhost:7357/assets/test-support.js:2750:28)
    at Object.Test.run (http://localhost:7357/assets/test-support.js:2735:4)
    at http://localhost:7357/assets/test-support.js:2877:11
    at process (http://localhost:7357/assets/test-support.js:2537:24)
    at begin (http://localhost:7357/assets/test-support.js:2519:2)
    at http://localhost:7357/assets/test-support.js:2579:4```

**Comment by Lydias303** [comment]
Still having this issue. Would love some help debugging!

**Comment by tim-evans** [comment]
What's the version of Ember you're using?

**Comment by Lydias303** [comment]
"ember-cli": "2.8.0",   "ember-plupload": "1.13.17",

**Comment by tim-evans** [comment]
Thanks! Lemme check this out

**Comment by pleszkowicz** [comment]
Hey guys! I have the same problem.
I'm using:
```
"ember-": "2.9.1"
"ember-cli": "2.9.1
"ember-plupload": "1.13.17"
```
The problem is here:
https://github.com/tim-evans/ember-plupload/blob/master/addon/test-helper.js#L93
Passed `owner` has no `lookup()` method.
I tried to pass `this.application.get('__container__')` (I know - it is deprecated / inconvenient), but later on I got new errors... like that I'm sendAction of undefined.
Hence I stopped further investigation.

**Comment by john-griffin** [comment]
Also just hit this.

**Comment by tim-evans** [comment]
This is totally deprecated. I will see if I can use `owner` 👍  Help to fix this would be amaaazing

**Comment by ashrafhasson** [comment]
I'm facing a similar issue with ember-cli 2.5.1. Using `this.application.__container__` in the acceptance test seems to get me past the issue of looking up `owner` but the test fails to trigger my component's target.

Test generates this message: 

`undefined is not an object (evaluating 'get(this, 'target').sendAction')`

Not sure if this is caused by the issue above. Would be great is someone can provide a hint, please.

**Comment by tim-evans** [comment]
Ahh, yes. Sorry about not taking care of this in a timely manner

**Comment by tim-evans** [comment]
I've been using `ember-file-upload` in projects and have been neglecting this. So, it's probably good to note that if someone would like to maintain this, that would be 👍 👍 👍

I will add patches here and there for support
